## Month 2 Week 2

### Hospital Management System

#### CRUD - Create, Read, Update, Delete

In [10]:
import pandas as pd

In [1]:
hospital_db = {
    'patients':[]
}

In [2]:
def add_patient(name, age, gender, condition):
    patient = {
        'id':len(hospital_db['patients']) + 1,
        'name':name,
        'age':age,
        'gender':gender,
        'condition':condition
    }
    hospital_db['patients'].append(patient)
    print (f'{name} has been added successfully')

In [8]:
add_patient('Jemima', 22, 'Female', 'Ulcer')

Jemima has been added successfully

In [18]:
def view_patient():
    if len(hospital_db['patients']) == 0:
        print('No patient records found')
        return
    df = pd.DataFrame(hospital_db['patients'])
    display(df) # It retains the normal data structure

In [19]:
view_patient()

   id     name  age  gender condition
0   1  Micheal   20    Male   Malaria
1   2   Daniel   23    Male     Cough
2   3   Jemima   22  Female     Ulcer

In [23]:
# Access the list of dictionaries then target the one of interest
def update_patient(patient_id,key,new_value):
    for patient in hospital_db['patients']:
        if patient['id'] == patient_id:
            patient[key] = new_value
            print(f'Patient ID {patient_id} updated successfully')
            view_patient()
            return
    print('Patient not found')

In [25]:
update_patient(2,'age',25 )

Patient not found

In [22]:
view_patient()

   id     name  age  gender condition
0   1  Micheal   20    Male   Malaria
1   2   Daniel   24    Male     Cough
2   3   Jemima   22  Female     Ulcer

In [28]:
#TODO: Write a function that update multiple key
# hospital_db['patients'][1].update({'age':30, 'condition':'Recovered'})

In [29]:
def delete_patient(patient_id):
    for patient in hospital_db['patients']:
        if patient['id'] == patient_id:
            hospital_db['patients'].remove(patient)
            print(f'Patient ID {patient_id} has been deleted')
            view_patient()
            return
    else:
        print('Patient not found')

In [30]:
delete_patient(2)

Patient ID 2 has been deleted

In [31]:
view_patient()

   id     name  age  gender condition
0   1  Micheal   20    Male   Malaria
1   3   Jemima   22  Female     Ulcer

In [32]:
# Main Menu
def main_menu():
    while True:
        print('\n============ Hospital Management System =============')
        print ('1 - Add Patient')
        print('2 - View Patient')
        print('3 - Update Patient')
        print('4 - Delete Patient')
        print('5 - Exit')

        choice = input('Enter your choice')
        if choice == '1':
            name = input('Enter Patient Name: ')
            age = int(input('Enter age: '))
            gender = input('Enter patient gender (M/F): ')
            condition = input('Enter patient condition: ')

            add_patient(name,age,gender,condition)

        elif choice == '2':
            view_patient()

        elif choice == '3':
            patient_id = int(input('Enter patient ID: '))
            key = input('Enter the key you wish to update: ')
            new_value = input(f'Enter the new value you wish to update {key}: ')

            update_patient(patient_id,key,new_value)

        elif choice == '4':
            patient_id = int(input('Enter patient ID: '))

            delete_patient(patient_id)

        elif choice == '5':
            print('Exiting the program...')
            break

        else:
            print('Invalid choice, Enter a number between 1 - 5')

============ Hospital Management System =============
1 - Add Patient
2 - View Patient
3 - Update Patient
4 - Delete Patient
5 - Exit

   id     name  age  gender condition
0   1  Micheal   20    Male   Malaria
1   3   Jemima   22  Female     Ulcer

============ Hospital Management System =============
1 - Add Patient
2 - View Patient
3 - Update Patient
4 - Delete Patient
5 - Exit

   id     name  age  gender condition
0   1  Micheal   20    Male   Malaria
1   3   Jemima   22  Female     Ulcer

============ Hospital Management System =============
1 - Add Patient
2 - View Patient
3 - Update Patient
4 - Delete Patient
5 - Exit
Invalid choice, Enter a number between 1 - 5

============ Hospital Management System =============
1 - Add Patient
2 - View Patient
3 - Update Patient
4 - Delete Patient
5 - Exit
Yaga has been added successfully

============ Hospital Management System =============
1 - Add Patient
2 - View Patient
3 - Update Patient
4 - Delete Patient
5 - Exit

   id     name  age  gender condition
0   1  Micheal   20    Male   Malaria
1   3   Jemima   22  Female     Ulcer
2   3     Yaga   10       M      Junk

============ Hospital Management System =============
1 - Add Patient
2 - View Patient
3 - Update Patient
4 - Delete Patient
5 - Exit
Exiting the program...

In [ ]:
# TODO: Add ward number